[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "funsearch"
version = "0.1.0"
description = "FunSearch package"
requires-python = ">=3.11"
dependencies = [
  "numpy",
  "scipy",
  "transformers",
  "openai",
  "aio-pika",
  "yarl",
  "psutil",
  "GPUtil",
  "memory-profiler",
  "cloudpickle"
]

[tool.setuptools.packages.find]
where = ["src"]
