version: '3.8'

services:
  funsearch-main:
    build:
      context: ..  # Use project root as build context
      dockerfile: .devcontainer/Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive
    container_name: "funsearch-main"
    tty: true
    privileged: false 
    volumes:
      - ~/.ssh:/root/.ssh  # Maps SSH folder (works across different users)
      - ../:/workspace/funsearch  # Mounts the project directory dynamically
      - /media/:/media/
      - /srv/:/srv/
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  rabbitmq:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.rabbitmq
    container_name: "rabbitmq"
    ports:
      - "6061:5672"
      - "16061:15672"
    volumes:
      - ../rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_ADVANCED_CONFIG_FILE=/etc/rabbitmq/advanced.config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
