version: '3.8'

services:
  disfun-main:
    build:
      context: ..  # Use project root as build context
      dockerfile: .devcontainer/Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive
    container_name: "disfun-main"
    tty: true
    privileged: false 
    volumes:
      - ~/.ssh:/root/.ssh
      - ../:/workspace/DistributedFunSearch  # Mount project root (host) into /workspace/DistributedFunSearch (container)
      - /mnt/hdd_pool_zion/users/franziska/Checkpoints/Graphs:/mnt/graphs/    # optional graph dir
      - /srv/:/srv/
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: /workspace/DistributedFunSearch  
    command: /bin/bash                 

  rabbitmq:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.rabbitmq
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_ADVANCED_CONFIG_FILE=/etc/rabbitmq/advanced.config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
